<?php
/**
 * @var \Magenable\PurchasePartnerUrl\Block\PartnerUrl $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $products = $block->getProducts(); ?>
<?php if (count($products)): ?>
<script>
    if (!window.magenable) {
        window.magenable = {};
    }
    window.magenable.purchasePartnerUrls = {};
    <?php foreach ($products as $product) { ?>
    window.magenable.purchasePartnerUrls[<?= $product->getId() ?>] = '<?= $escaper->escapeJs($product->getMagenablePurchasePartnerUrl()) ?>';
    <?php } ?>
</script>
<?php endif; ?>
