<?php
/**
 * @var \Magenable\PurchasePartnerUrl\Block\Product\ListProduct $block
 */

/** @var $viewModel \Magenable\PurchasePartnerUrl\ViewModel\ViewModel */
$viewModel = $block->getViewModel();
/** @var $escaper \Magento\Framework\Escaper */
$escaper = $viewModel->getEscaper();
?>
<div class="product-item-purchase-partner"
     data-mage-init='{
        "Magenable_PurchasePartnerUrl/js/google-analytics": {
            "analitycsIsEnabled": <?= $escaper->escapeJs($viewModel->analyticsIsEnabled()) ?>,
            "isOpenLinkInNewTab": <?= $escaper->escapeJs($viewModel->isOpenLinkInNewTab()) ?>
        }
    }'
>
    <?php foreach ($block->getPurchasePartnerUrls() as $purchasePartnerUrl): ?>
        <?php $buttonTitle = $purchasePartnerUrl['link_title'] ?: $viewModel->getDefaultButtonTitle(); ?>
        <?php $eventCategory = $purchasePartnerUrl['event_category'] ?: $viewModel->getDefaultEventCategory(); ?>
        <?php $eventAction = $purchasePartnerUrl['event_action'] ?: $viewModel->getDefaultEventAction(); ?>
        <?php $price = $block->getProduct()->getPrice(); ?>
    <button type="button"
            title="<?= $escaper->escapeHtmlAttr($buttonTitle) ?>"
            class="action primary magenable-purchase-partner-url"
            data-link="<?= $escaper->escapeHtmlAttr($purchasePartnerUrl['link']) ?>"
            data-event-category="<?= $escaper->escapeHtmlAttr($eventCategory) ?>"
            data-event-action="<?= $escaper->escapeHtmlAttr($eventAction) ?>"
            data-event-value="<?= $escaper->escapeHtmlAttr($block->getEventValue()) ?>">
        <span><?= $escaper->escapeHtml($buttonTitle) ?></span>
    </button>
    <?php endforeach; ?>
</div>
