<?php
/**
 * @var \Magenable\PurchasePartnerUrl\Block\Product\View $block
 */

/** @var $viewModel \Magenable\PurchasePartnerUrl\ViewModel\ViewModel */
$viewModel = $block->getViewModel();
/** @var $escaper \Magento\Framework\Escaper */
$escaper = $viewModel->getEscaper();
?>
<div class="box-tocart"
    data-mage-init='{
        "Magenable_PurchasePartnerUrl/js/google-analytics": {
            "analitycsIsEnabled": <?= $escaper->escapeJs($viewModel->analyticsIsEnabled()) ?>,
            "isOpenLinkInNewTab": <?= $escaper->escapeJs($viewModel->isOpenLinkInNewTab()) ?>
        }
    }'
>
    <div class="fieldset">
        <div class="actions product-item-purchase-partner">
            <button type="button"
                    title="<?= $escaper->escapeHtmlAttr($viewModel->getDefaultButtonTitle()) ?>"
                    class="action primary">
                <span>
                    <?= $escaper->escapeHtml($viewModel->getDefaultButtonTitle()) ?>
                </span>
            </button>
            <div class="magenable-purchase-partner-urls-wrapper hidden">
                <?php foreach ($block->getPurchasePartnerUrls() as $purchasePartnerUrl): ?>
                    <?php
                        $buttonTitle = $purchasePartnerUrl['link_title'] ?: $viewModel->getDefaultButtonTitle();
                        $eventCategory = $purchasePartnerUrl['event_category'] ?: $viewModel->getDefaultEventCategory();
                        $eventAction = $purchasePartnerUrl['event_action'] ?: $viewModel->getDefaultEventAction();
                    ?>
                    <button class="action primary magenable-purchase-partner-url"
                            data-link="<?= $escaper->escapeHtmlAttr($purchasePartnerUrl['link']) ?>"
                            data-event-category="<?= $escaper->escapeHtmlAttr($eventCategory) ?>"
                            data-event-action="<?= $escaper->escapeHtmlAttr($eventAction) ?>"
                            data-event-value="<?= $escaper->escapeHtmlAttr($block->getEventValue()) ?>">
                        <?= $escaper->escapeHtml($buttonTitle) ?>
                    </button>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

